<x-docs-props :rows="[
    ['label', 'string | null', 'null', 'Visible label; omitted when empty.'],
    ['helper', 'string | null', 'null', 'Supporting text below the control.'],
    ['thousands-separator', ', | . |   | \'', 'sirius-ui.currency.thousands_separator → ,', 'Explicit props override global configuration. Thousands separator for display, must differ from the decimal separator.'],
    ['decimal-separator', '. | ,', 'sirius-ui.currency.decimal_separator → .', 'Explicit props override global configuration. Decimal separator for display, canonical values always use dot (.), must differ from the thousands separator.'],
    ['precision', 'integer', 'sirius-ui.currency.precision → 2', 'Explicit props override global configuration, including zero. Maximum fractional digits, 0 through 20. Excess digits stay visible and canonical but fail client validity: never rounded or truncated. No automatic zero padding.'],
    ['allow-negative', 'boolean', 'false', 'Allows a leading minus sign. A sign is rejected during editing when false.'],
    ['prefix', 'string | null', 'null', 'Text or named slot before the input. The slot overrides the prop; adornments are excluded from submission.'],
    ['suffix', 'string | null', 'null', 'Text or named slot after the input. The slot overrides the prop; adornments are excluded from submission.'],
    ['size', 'sm | md | lg', 'md', 'Visual size (font and padding), independent of the native HTML size attribute.'],
    ['control-size', 'integer | null', 'null', 'Native HTML size attribute: approximate width in characters, subject to CSS. Does not limit input length.'],
    ['error-key', 'string | null', 'null', 'Override the validation key; otherwise use the wire:model path, then the normalized name.'],
    ['error-bag', 'string', 'default', 'Named Laravel validation error bag.'],
    ['errors', 'ViewErrorBag | null', 'null', 'Optional explicit error bags; otherwise supplied by Laravel or Livewire.'],
    ['wrapper-class', 'string', 'empty string', 'Additional CSS classes for the field wrapper.'],
]" />
