<x-docs-props :rows="[
    ['label', 'string | null', 'null', 'Visible label; omitted when empty.'],
    ['helper', 'string | null', 'null', 'Supporting text below the control.'],
    ['thousands-separator', ', | . |   | \'', ',', 'Thousands separator for display, must differ from the decimal separator.'],
    ['decimal-separator', '. | ,', '.', 'Decimal separator for display, canonical values always use dot (.), must differ from the thousands separator.'],
    ['precision', 'integer', '2', 'Maximum fractional digits, 0 through 20. Excess digits stay visible and canonical but fail client validity: never rounded or truncated. No automatic zero padding.'],
    ['allow-negative', 'boolean', 'false', 'Allows a leading minus sign. A sign is rejected during editing when false.'],
    ['prefix', 'string | null', 'null', 'Text or named slot adornments in front of the currency input. Slots override strings.'],
    ['suffix', 'string | null', 'null', 'Text or named slot adornments in end of the currency input. Slots override strings.'],
    ['size', 'sm | md | lg', 'md', 'Shared field sizing.'],
    ['control-size', 'integer | null', 'null', 'Native input size attribute; separate from visual size.'],
    ['error-key', 'string | null', 'null', 'Override the validation key; otherwise use the wire:model path, then normalized name.'],
    ['error-bag', 'string', 'default', 'Laravel named validation bag. Choice groups share their parent bag.'],
    ['errors', 'ViewErrorBag | null', 'null', 'Optional explicit error bag; otherwise supplied by Laravel/Livewire.'],
    ['wrapper-class', 'string', '', 'Customize the field wrapper class.'],
]" />
