<x-docs-props :rows="[
    ['type', 'date | time | datetime', 'date', 'Single selection, with a calendar prefix for date/datetime and a clock prefix for time. Canonical strings use Y-m-d, H:i, or Y-m-d H:i:s respectively.'],
    ['display-format', 'string', 'd/m/Y; H:i; d/m/Y H:i:S', 'Flatpickr format tokens; uppercase S displays seconds. Use a format retaining all parts needed by the selected type.'],
    ['timezone', 'IANA timezone', 'sirius-ui.timezone → app.timezone → UTC', 'Global configuration is used unless this prop overrides it. Context for the initial day/time; no automatic UTC conversion.'],
    ['locale', 'string', 'sirius-ui.locale → app.locale → app.fallback_locale → en', 'Priority: explicit prop, options.locale, global package locale, application locale, application fallback locale, then en. Regional codes retain an exact bundled locale or fall back to their language: id_ID → id, en-GB → en, zh-TW → zh_tw. Unsupported languages are rejected; set a supported override.'],
    ['week-start', 'integer | null', 'locale default', 'First weekday: 0 (Sunday) through 6 (Saturday).'],
    ['minute-increment', 'integer', '5', 'Time spinner increment, 1–60; not a server-side restriction on submitted minutes.'],
    ['min-date / max-date', 'string | null', 'null', 'Inclusive bounds in canonical date/datetime format; unavailable in time type.'],
    ['min-time / max-time', 'string | null', 'null', 'Inclusive H:i bounds for time/datetime. Overnight ranges are rejected.'],
    ['disabled-dates', 'array', '[]', 'Unavailable Y-m-d dates for date/datetime. Validate equivalent restrictions on the server.'],
    ['clearable', 'boolean', '!required', 'Explicit values override the default: false for required fields, true for optional fields. Show the Clear icon in the styled suffix; does not prevent keyboard deletion or reset when false.'],
    ['options', 'array', '[]', 'Compatible Flatpickr options: minDate, maxDate, minTime, maxTime, disable, locale, minuteIncrement, hourIncrement, time_24hr, weekNumbers, showMonths, monthSelectorType, position, shorthandCurrentMonth, ariaDateFormat, defaultHour, defaultMinute. Defaults, then options, then explicit non-null props determine precedence. Other options are rejected.'],
    ['label', 'string | null', 'null', 'Visible label; omitted when empty.'],
    ['helper', 'string | null', 'null', 'Supporting text below the control.'],
    ['error-key', 'string | null', 'null', 'Overrides error lookup from the binding or normalized name.'],
    ['error-bag', 'string', 'default', 'Laravel named validation bag. Choice groups share their parent bag.'],
    ['errors', 'ViewErrorBag | null', 'null', 'Optional explicit error bag; otherwise supplied by Laravel/Livewire.'],
    ['size', 'sm | md | lg', 'md', 'Visual sizing, independent from the native size attribute.'],
    ['wrapper-class', 'string', 'empty', 'Additional classes for the field wrapper.'],
]" note="Applicable input HTML5, Alpine event directives, data-*, ARIA attributes, and supported Livewire directives (such as wire:model and its modifiers) are supported as expected and forwarded to the native control. Lifecycle and type attributes remain package-owned." />
