<x-docs-props :rows="[
    ['options', 'array', '[]', 'List of records with a unique non-empty value and a label; optional disabled boolean and group label. Integer values become strings.'],
    ['value', 'string | integer | array | null', 'null', 'Initial selected ID or list of IDs in multiple mode. Empty single values bind null; empty multiple values bind an empty array.'],
    ['multiple', 'boolean', 'false', 'Allow multiple selected IDs; a native field name receives [] automatically.'],
    ['placeholder', 'string', 'Select an option', 'Prompt displayed when no value is selected.'],
    ['searchable', 'boolean', 'true', 'Allow typing to filter local options or search the configured endpoint.'],
    ['clearable', 'boolean | null', '!required', 'Allow Clear and keyboard removal; an explicit value overrides the required-derived default. Multiple select will always set this to true.'],
    ['search-url', 'string | null', 'null', 'Same-origin GET endpoint for remote search, pagination, and selected-label resolution.'],
    ['debounce', 'integer', '300', 'Remote search delay in milliseconds, from 0 to 10000.'],
    ['min-search-length', 'integer', '0', 'Minimum query length for remote search, from 0 to 100.'],
    ['max-items', 'integer | null', 'null', 'Positive maximum number of selected items in multiple mode; null is unlimited.'],
    ['label', 'string | null', 'null', 'Visible label; omitted when empty.'],
    ['helper', 'string | null', 'null', 'Supporting text below the control.'],
    ['error-key', 'string | null', 'null', 'Override the validation key; otherwise use the wire:model path, then the normalized name.'],
    ['error-bag', 'string', 'default', 'Named Laravel validation error bag.'],
    ['errors', 'ViewErrorBag | null', 'null', 'Optional explicit error bags; otherwise supplied by Laravel or Livewire.'],
    ['size', 'sm | md | lg', 'md', 'Visual size (font and padding), independent of the native HTML size attribute.'],
    ['wrapper-class', 'string', 'empty string', 'Additional CSS classes for the field wrapper.'],
]" note="Applicable select HTML5, Alpine event directives, data-*, ARIA attributes, and supported Livewire directives (such as wire:model and its modifiers) are supported as expected. Lifecycle and type attributes remain package-owned. Native attributes belong to the submitted select; labels, descriptions, errors, required, readonly, and disabled state also reach the enhanced control. Model bindings use a separate bridge with string IDs and arrays; number, boolean, and trim modifiers are unsupported. Readonly is enforced by the JavaScript adapter." />
